Fix: ERROR in ./src/spec.ts (6,27): error TS2339: Property 'context' does not exist on type 'NodeRequire'. Don't include type definitions for '@angular/platform-browser'. Remove not used type definitions for 'webpack'.